#!/bin/sh
#
# Disable start gsmmodemd
#

DAEMON=gsmmodemd

start() {
	printf "Starting ${DAEMON}: "
    echo "disabled"

    slog.sh "GSM Modem disabled"
}

stop() {
	printf "Stopping ${DAEMON}: "
    echo "disabled"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0

