#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
 	if [ -f /etc/sysctl.conf -a -x /sbin/sysctl ]
  then
      echo "Running sysctl..."
      sysctl -p /etc/sysctl.conf >/dev/null 2>&1
  fi
	/sbin/ifup -a
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

